apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-serving
  template:
    metadata:
      labels:
        app: ml-serving
    spec:
      containers:
      - name: ml-serving
        image: aksmlopscourse.azurecr.io/mlapp:latest
       # image: pzdesign/ml-serving
        ports:
        - containerPort: 8501
---      
apiVersion: v1
kind: Service
metadata:
  name: ml-serving
spec:
  ports:
  - port: 8501
    nodePort: 30111
  selector:
    app: ml-serving
  type: NodePort
