FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 30001

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["KubernetesDemoApp/KubernetesDemoApp.csproj", "KubernetesDemoApp/"]
RUN dotnet restore "KubernetesDemoApp/KubernetesDemoApp.csproj"
COPY . .
WORKDIR "/src/KubernetesDemoApp"
RUN dotnet build "KubernetesDemoApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "KubernetesDemoApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KubernetesDemoApp.dll"]