version: '3.4'

services:  
  ordering.api:
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings__ConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
   ports:
     - "8091:80"

   depends_on:
     - db

  customer.api:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=customerdb;Database=CustomerDb;User Id=sa;Password=SwN12345678;"
   ports:
     - "8092:80"
   depends_on:
     - db

  db:
   container_name: DB
   environment:
       SA_PASSWORD: "SwN12345678"
       ACCEPT_EULA: "Y"
   restart: always
   ports:
       - "1433:1433"
