version: '3.4'

services:  
  ordering.api:
   image: ${DOCKER_REGISTRY-}orderingapi
   build:
     context: .
     dockerfile: Microservices/Ordering/Ordering.API/Dockerfile
     args:
       - NUGET_PAT

  customer.api:
   image: ${DOCKER_REGISTRY-}customerapi
   build:
     context: .
     dockerfile: Microservices/Customer/Customer.API/Dockerfile
     args:
       - NUGET_PAT

  db:
   container_name: DB
   environment:
       SA_PASSWORD: "SwN12345678"
       ACCEPT_EULA: "Y"
   restart: always
   ports:
       - "1433:1433"
