---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:  # Add the selector here to match the template labels
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              value: {{ .Values.cassandra.seeds }}
            - name: MAX_HEAP_SIZE
              value: {{ .Values.cassandra.maxHeapSize }}
            - name: HEAP_NEWSIZE
              value: {{ .Values.cassandra.heapNewSize }}
            - name: CASSANDRA_CLUSTER_NAME
              value: {{ .Values.cassandra.clusterName }}
            - name: CASSANDRA_DC
              value: {{ .Values.cassandra.dc }}
            - name: CASSANDRA_RACK
              value: {{ .Values.cassandra.rack }}
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: {{ .Values.cassandra.endpointSnitch }}
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
        annotations:  # comment line if you want to use a StorageClass
          # or specify which StorageClass
          volume.beta.kubernetes.io/storage-class: ""   # comment line if you
          # want to use a StorageClass or specify which StorageClass
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi