apiVersion: v1
kind: Service
metadata:
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
    app: cassandra
  annotations:
    meta.helm.sh/release-name: cassandra
    meta.helm.sh/release-namespace: default
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra