---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-1
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
    app: cassandra
  annotations:
    meta.helm.sh/release-name: cassandra
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-2
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
    app: cassandra
  annotations:
    meta.helm.sh/release-name: cassandra
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data-2
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-3
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
    app: cassandra
  annotations:
    meta.helm.sh/release-name: cassandra
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-data-3
  persistentVolumeReclaimPolicy: Recycle